version: 2
project_name: diverge
builds:
  - id: diverge-controller
    main: cmd/controller/main.go
    binary: diverge-controller
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge-controller-slim
    main: cmd/controller/main.go
    binary: diverge-controller
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    tags:
      - no_knative
      - no_schema
      - no_temporal
      - no_kafka
  - id: diverge
    main: cmd/diverge/main.go
    binary: diverge
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge-slim
    main: cmd/diverge/main.go
    binary: diverge
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    tags:
      - no_knative
      - no_schema
      - no_temporal
      - no_kafka
  - id: diverge-proxy
    main: cmd/proxy/main.go
    binary: diverge-proxy
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge-activator-proxy
    main: cmd/activator-proxy/main.go
    binary: diverge-activator-proxy
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge-server
    main: cmd/server/main.go
    binary: diverge-server
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - id: full
    format: tar.gz
    builds:
      - diverge
      - diverge-controller
      - diverge-proxy
      - diverge-activator-proxy
      - diverge-server
    files:
      - src: README*
      - src: LICENSE*
  - id: slim
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_slim_{{ .Os }}_{{ .Arch }}"
    builds:
      - diverge-slim
      - diverge-controller-slim
    files:
      - src: README*
      - src: LICENSE*
dockers:
  - id: diverge-amd64
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    ids:
      - diverge-controller
      - diverge-proxy
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - id: diverge-arm64
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    ids:
      - diverge-controller
      - diverge-proxy
    build_flag_templates:
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
  - id: diverge-slim-amd64
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    ids:
      - diverge-controller-slim
      - diverge-proxy
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - id: diverge-slim-arm64
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    ids:
      - diverge-controller-slim
      - diverge-proxy
    build_flag_templates:
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
  - id: activator-proxy-amd64
    image_templates:
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.activator-proxy
    use: buildx
    ids:
      - diverge-activator-proxy
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - id: activator-proxy-arm64
    image_templates:
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.activator-proxy
    use: buildx
    ids:
      - diverge-activator-proxy
    build_flag_templates:
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
docker_manifests:
  - name_template: "ghcr.io/divergedev/diverge:{{ .Tag }}"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/divergedev/diverge:latest"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/divergedev/diverge:{{ .Tag }}-slim"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-arm64"
  - name_template: "ghcr.io/divergedev/diverge:slim"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-slim-arm64"
  - name_template: "ghcr.io/divergedev/activator-proxy:{{ .Tag }}"
    image_templates:
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/divergedev/activator-proxy:latest"
    image_templates:
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/activator-proxy:{{ .Tag }}-arm64"
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: divergedev
    name: diverge
