version: 2
project_name: diverge
builds:
  - id: diverge-controller
    main: cmd/controller/main.go
    binary: diverge-controller
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge
    main: cmd/diverge/main.go
    binary: diverge
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: diverge-proxy
    main: cmd/proxy/main.go
    binary: diverge-proxy
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - format: tar.gz
    files:
      - src: README*
      - src: LICENSE*
dockers:
  - image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    extra_files:
      - diverge-controller
      - diverge-proxy
  - image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: arm64
    extra_files:
      - diverge-controller
      - diverge-proxy
docker_manifests:
  - name_template: "ghcr.io/divergedev/diverge:{{ .Tag }}"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/divergedev/diverge:latest"
    image_templates:
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-amd64"
      - "ghcr.io/divergedev/diverge:{{ .Tag }}-arm64"
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
release:
  github:
    owner: divergedev
    name: diverge
