# alpine:3.20
FROM alpine@sha256:d9e853e87e55526f6b2917df91a2115c36dd7c696a35be12163d44e6e2a4b6bc
RUN apk add --no-cache git curl jq bash \
    && adduser -D -u 1000 diverge
COPY diverge /usr/local/bin/diverge
USER 1000:1000
ENTRYPOINT ["diverge"]
