FROM golang:1.26 AS builder

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY cmd/proxy/ cmd/proxy/
COPY api/ api/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o diverge-proxy cmd/proxy/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/diverge-proxy .
USER 65532:65532

EXPOSE 8090
ENTRYPOINT ["/diverge-proxy"]
