# gcr.io/distroless/static:nonroot
FROM gcr.io/distroless/static@sha256:1c2c046bc09ed40fad370b599a0b1ae7987f55b01e247cf27a7c27cd97e5bbc7
COPY diverge-controller /diverge-controller
COPY diverge-server /diverge-server
COPY diverge-proxy /diverge-proxy
USER 65532:65532
ENTRYPOINT ["/diverge-controller"]
