package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	divergev1alpha1 "github.com/divergedev/diverge/api/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type ConfigWatcher struct {
	crdClient   client.Client
	pgName      string
	envFile     string
	lastEnvHash string
	mu          sync.Mutex
}

func NewConfigWatcher(crdClient client.Client, pgName string, envFile string) *ConfigWatcher {
	return &ConfigWatcher{
		crdClient: crdClient,
		pgName:    pgName,
		envFile:   envFile,
	}
}

func (cw *ConfigWatcher) Watch(ctx context.Context) error {
	// Poll PreviewGroup status every 5 seconds
	// (Using polling instead of informer since CLI may not have watch RBAC on CRDs)
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	// Initial sync
	cw.syncOnce(ctx)

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-ticker.C:
			cw.syncOnce(ctx)
		}
	}
}

func (cw *ConfigWatcher) syncOnce(ctx context.Context) {
	// Use a short timeout per poll to avoid blocking the loop if API server is slow
	pollCtx, pollCancel := context.WithTimeout(ctx, 5*time.Second)
	defer pollCancel()

	var pg divergev1alpha1.PreviewGroup
	err := cw.crdClient.Get(pollCtx, client.ObjectKey{Name: cw.pgName}, &pg)
	if err != nil {
		return // PG may not exist yet or may be deleted
	}

	envMap := cw.buildEnvMap(&pg)
	cw.writeEnvFile(envMap)
}

func (cw *ConfigWatcher) buildEnvMap(pg *divergev1alpha1.PreviewGroup) map[string]string {
	env := make(map[string]string)

	// Routing metadata
	env["DIVERGE_PREVIEW_ID"] = pg.Name
	if pg.Spec.Routing.HeaderKey != "" {
		env["DIVERGE_HEADER_KEY"] = pg.Spec.Routing.HeaderKey
	}
	if pg.Spec.Routing.HeaderValue != "" {
		env["DIVERGE_HEADER_VALUE"] = pg.Spec.Routing.HeaderValue
	}

	// Service endpoints from status
	for _, svc := range pg.Status.Services {
		if svc.URL != "" {
			key := fmt.Sprintf("DIVERGE_SVC_%s_URL", strings.ToUpper(strings.ReplaceAll(svc.Name, "-", "_")))
			env[key] = svc.URL
		}
	}

	return env
}

func (cw *ConfigWatcher) writeEnvFile(envMap map[string]string) {
	// Build content
	keys := make([]string, 0, len(envMap))
	for k := range envMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by diverge dev - do not edit\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, envMap[k])
	}

	content := sb.String()

	// Only write if changed
	cw.mu.Lock()
	defer cw.mu.Unlock()
	if content == cw.lastEnvHash {
		return
	}

	// Write atomically: temp file + rename to avoid partial reads by hot-reloaders
	dir := filepath.Dir(cw.envFile)
	tmpFile, err := os.CreateTemp(dir, ".env.diverge.tmp.*")
	if err != nil {
		return
	}
	tmpName := tmpFile.Name()

	if _, err := tmpFile.WriteString(content); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmpName)
		return
	}
	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpName)
		return
	}
	if err := os.Rename(tmpName, cw.envFile); err != nil {
		_ = os.Remove(tmpName)
		return
	}

	old := cw.lastEnvHash
	cw.lastEnvHash = content

	if old != "" {
		fmt.Printf("[diverge] 🔄 Routing config updated, wrote %s\n", cw.envFile)
	}
}
