package cli

import (
	"context"
	"os"
	"testing"

	divergev1alpha1 "github.com/divergedev/diverge/api/v1alpha1"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

func TestConfigWatcher_buildEnvMap(t *testing.T) {
	pg := &divergev1alpha1.PreviewGroup{
		ObjectMeta: metav1.ObjectMeta{
			Name: "my-pg",
		},
		Spec: divergev1alpha1.PreviewGroupSpec{
			Routing: divergev1alpha1.PreviewGroupRouting{
				HeaderKey:   "x-env",
				HeaderValue: "test",
			},
		},
		Status: divergev1alpha1.PreviewGroupStatus{
			Services: []divergev1alpha1.PreviewGroupServiceStatus{
				{
					Name: "user-svc",
					URL:  "http://user-svc:8080",
				},
				{
					Name: "cart-svc",
					URL:  "http://cart-svc:8081",
				},
			},
		},
	}

	cw := NewConfigWatcher(nil, "my-pg", "")
	envMap := cw.buildEnvMap(pg)

	assert.Equal(t, "my-pg", envMap["DIVERGE_PREVIEW_ID"])
	assert.Equal(t, "x-env", envMap["DIVERGE_HEADER_KEY"])
	assert.Equal(t, "test", envMap["DIVERGE_HEADER_VALUE"])
	assert.Equal(t, "http://user-svc:8080", envMap["DIVERGE_SVC_USER_SVC_URL"])
	assert.Equal(t, "http://cart-svc:8081", envMap["DIVERGE_SVC_CART_SVC_URL"])
}

func TestConfigWatcher_writeEnvFile(t *testing.T) {
	tmpFile, err := os.CreateTemp("", ".env.diverge.*")
	require.NoError(t, err)
	defer func() { _ = os.Remove(tmpFile.Name()) }()

	cw := NewConfigWatcher(nil, "my-pg", tmpFile.Name())

	envMap := map[string]string{
		"B_KEY": "val-b",
		"A_KEY": "val-a",
	}

	// Write first time
	cw.writeEnvFile(envMap)

	content, err := os.ReadFile(tmpFile.Name())
	require.NoError(t, err)

	expected := `# Generated by diverge dev - do not edit
A_KEY=val-a
B_KEY=val-b
`
	assert.Equal(t, expected, string(content))
}

func TestConfigWatcher_syncOnce(t *testing.T) {
	scheme := runtime.NewScheme()
	err := divergev1alpha1.AddToScheme(scheme)
	require.NoError(t, err)

	pg := &divergev1alpha1.PreviewGroup{
		ObjectMeta: metav1.ObjectMeta{
			Name: "my-pg",
		},
		Spec: divergev1alpha1.PreviewGroupSpec{
			Routing: divergev1alpha1.PreviewGroupRouting{
				HeaderKey:   "x-env",
				HeaderValue: "test",
			},
		},
		Status: divergev1alpha1.PreviewGroupStatus{
			Services: []divergev1alpha1.PreviewGroupServiceStatus{
				{
					Name: "user-svc",
					URL:  "http://user-svc:8080",
				},
			},
		},
	}

	fakeClient := fake.NewClientBuilder().WithScheme(scheme).WithObjects(pg).Build()

	tmpFile, err := os.CreateTemp("", ".env.diverge.*")
	require.NoError(t, err)
	defer func() { _ = os.Remove(tmpFile.Name()) }()

	cw := NewConfigWatcher(fakeClient, "my-pg", tmpFile.Name())

	cw.syncOnce(context.Background())

	content, err := os.ReadFile(tmpFile.Name())
	require.NoError(t, err)

	expected := `# Generated by diverge dev - do not edit
DIVERGE_HEADER_KEY=x-env
DIVERGE_HEADER_VALUE=test
DIVERGE_PREVIEW_ID=my-pg
DIVERGE_SVC_USER_SVC_URL=http://user-svc:8080
`
	assert.Equal(t, expected, string(content))
}
