package cli

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

// kubeInjectedPrefixes lists environment variable prefixes injected by Kubernetes
// that are not useful for local development.
var kubeInjectedPrefixes = []string{
	"KUBERNETES_",
	"_SERVICE_HOST",
	"_SERVICE_PORT",
	"_PORT_",
	"_PORT=",
}

// kubeInjectedExact lists exact env var names injected by Kubernetes.
var kubeInjectedExact = map[string]bool{
	"KUBERNETES_SERVICE_HOST": true,
	"KUBERNETES_SERVICE_PORT": true,
	"KUBERNETES_PORT":         true,
	"HOME":                    true,
	"HOSTNAME":                true,
	"PATH":                    true,
	"TERM":                    true,
}

// isKubeInjected returns true if the given env var name is injected by Kubernetes
// infrastructure and should be excluded from the local .env file.
func isKubeInjected(name string) bool {
	if kubeInjectedExact[name] {
		return true
	}
	upper := strings.ToUpper(name)
	for _, prefix := range kubeInjectedPrefixes {
		if strings.Contains(upper, prefix) {
			return true
		}
	}
	return false
}

// syncEnvOptions configures the env var sync behavior.
type syncEnvOptions struct {
	// Namespace is the K8s namespace to search for the baseline pod.
	Namespace string
	// ServiceName is the baseline service name to find pods for.
	ServiceName string
	// OutputPath is the file to write (default: .env.diverge).
	OutputPath string
}

// syncBaselineEnv reads environment variables from a running baseline pod
// and writes them to a local .env file for use during local development.
// It filters out Kubernetes-injected variables that are not useful locally.
func syncBaselineEnv(ctx context.Context, clientset kubernetes.Interface, opts syncEnvOptions) (int, error) {
	if opts.OutputPath == "" {
		opts.OutputPath = ".env.diverge"
	}

	// Find baseline pods by app label matching the service name
	labelSelectors := []string{
		fmt.Sprintf("app=%s,diverge.io/role=baseline", opts.ServiceName),
		fmt.Sprintf("app=%s", opts.ServiceName),
		fmt.Sprintf("app.kubernetes.io/name=%s", opts.ServiceName),
	}

	var pod *corev1.Pod
	for _, sel := range labelSelectors {
		pods, err := clientset.CoreV1().Pods(opts.Namespace).List(ctx, metav1.ListOptions{
			LabelSelector: sel,
			Limit:         1,
		})
		if err != nil {
			continue
		}
		if len(pods.Items) > 0 {
			pod = &pods.Items[0]
			break
		}
	}

	if pod == nil {
		return 0, fmt.Errorf("no baseline pod found for service %q in namespace %q", opts.ServiceName, opts.Namespace)
	}

	// Extract env vars from the first container
	if len(pod.Spec.Containers) == 0 {
		return 0, fmt.Errorf("pod %q has no containers", pod.Name)
	}

	container := pod.Spec.Containers[0]
	envMap := make(map[string]string)

	for _, env := range container.Env {
		if isKubeInjected(env.Name) {
			continue
		}
		// Skip vars sourced from secrets/configmaps (value will be empty,
		// and we can't resolve them from here without additional permissions)
		if env.ValueFrom != nil {
			envMap[env.Name] = fmt.Sprintf("# sourced from %s", describeValueSource(env.ValueFrom))
			continue
		}
		envMap[env.Name] = env.Value
	}

	if len(envMap) == 0 {
		return 0, nil
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(envMap))
	for k := range envMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Write .env file
	var sb strings.Builder
	sb.WriteString("# Generated by 'diverge dev' — env vars from baseline pod\n")
	sb.WriteString(fmt.Sprintf("# Source: %s/%s (container: %s)\n", pod.Namespace, pod.Name, container.Name))
	sb.WriteString("# Re-run 'diverge dev' to refresh.\n\n")

	written := 0
	for _, k := range keys {
		v := envMap[k]
		if strings.HasPrefix(v, "# sourced from") {
			sb.WriteString(fmt.Sprintf("# %s=%s\n", k, v))
		} else {
			sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
			written++
		}
	}

	if err := os.WriteFile(opts.OutputPath, []byte(sb.String()), 0644); err != nil {
		return 0, fmt.Errorf("failed to write %s: %w", opts.OutputPath, err)
	}

	return written, nil
}

// describeValueSource returns a human-readable description of where an env var
// value is sourced from (Secret, ConfigMap, etc).
func describeValueSource(vs *corev1.EnvVarSource) string {
	if vs.SecretKeyRef != nil {
		return fmt.Sprintf("secret:%s/%s", vs.SecretKeyRef.Name, vs.SecretKeyRef.Key)
	}
	if vs.ConfigMapKeyRef != nil {
		return fmt.Sprintf("configmap:%s/%s", vs.ConfigMapKeyRef.Name, vs.ConfigMapKeyRef.Key)
	}
	if vs.FieldRef != nil {
		return fmt.Sprintf("fieldRef:%s", vs.FieldRef.FieldPath)
	}
	if vs.ResourceFieldRef != nil {
		return fmt.Sprintf("resourceFieldRef:%s", vs.ResourceFieldRef.Resource)
	}
	return "unknown"
}
