package cli

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"sort"
	"strings"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/validation"
	"k8s.io/client-go/kubernetes"
)

// ErrBaselinePodNotFound is returned when no baseline pod can be found for the
// given service name and namespace.
var ErrBaselinePodNotFound = errors.New("no baseline pod found")

// ErrInvalidServiceName is returned when the service name is not a valid
// Kubernetes label value.
var ErrInvalidServiceName = errors.New("invalid service name")

// kubeInjectedPrefixes lists environment variable prefixes injected by Kubernetes
// that are not useful for local development.
var kubeInjectedPrefixes = []string{
	"KUBERNETES_",
	"_SERVICE_HOST",
	"_SERVICE_PORT",
	"_PORT_",
	"_PORT=",
}

// kubeInjectedExact lists exact env var names injected by Kubernetes.
var kubeInjectedExact = map[string]bool{
	"KUBERNETES_SERVICE_HOST": true,
	"KUBERNETES_SERVICE_PORT": true,
	"KUBERNETES_PORT":         true,
	"HOME":                    true,
	"HOSTNAME":                true,
	"PATH":                    true,
	"TERM":                    true,
}

// isKubeInjected returns true if the given env var name is injected by Kubernetes
// infrastructure and should be excluded from the local .env file.
func isKubeInjected(name string) bool {
	if kubeInjectedExact[name] {
		return true
	}
	upper := strings.ToUpper(name)
	for _, prefix := range kubeInjectedPrefixes {
		if strings.Contains(upper, prefix) {
			return true
		}
	}
	return false
}

type envEntry struct {
	Value  string
	Source string
}

type syncEnvOptions struct {
	// Namespace is the K8s namespace to search for the baseline pod.
	Namespace string
	// ServiceName is the baseline service name to find pods for.
	ServiceName string
}

// syncBaselineEnvToFile writes environment variables from a baseline pod to a file.
// Deprecated: Use syncBaselineEnv with a buffer or stdout instead to avoid writing secrets to disk.
func syncBaselineEnvToFile(ctx context.Context, clientset kubernetes.Interface, opts syncEnvOptions, filePath string) (n int, err error) {
	if filePath == "" {
		filePath = ".env.diverge"
	}
	f, err := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return 0, err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()
	fmt.Fprintf(os.Stderr, "⚠️  Writing secrets to disk is deprecated. Use --env-output inject instead.\n")
	return syncBaselineEnv(ctx, clientset, opts, f)
}

// syncBaselineEnv reads environment variables from a running baseline pod
// and writes them to out for use during local development.
// It filters out Kubernetes-injected variables that are not useful locally.
func syncBaselineEnv(ctx context.Context, clientset kubernetes.Interface, opts syncEnvOptions, out io.Writer) (int, error) {
	// Validate service name before using in label selectors
	if opts.ServiceName == "" {
		return 0, fmt.Errorf("%w: must not be empty", ErrInvalidServiceName)
	}
	if errs := validation.IsValidLabelValue(opts.ServiceName); len(errs) > 0 {
		return 0, fmt.Errorf("%w: %q: %s", ErrInvalidServiceName, opts.ServiceName, strings.Join(errs, "; "))
	}

	pod, err := findBaselinePod(ctx, clientset, opts.Namespace, opts.ServiceName)
	if err != nil {
		return 0, err
	}

	// Extract env vars from the first container
	if len(pod.Spec.Containers) == 0 {
		return 0, fmt.Errorf("pod %q has no containers", pod.Name)
	}

	container := pod.Spec.Containers[0]
	envMap := make(map[string]envEntry)

	for _, env := range container.Env {
		if isKubeInjected(env.Name) {
			continue
		}
		// Skip vars sourced from secrets/configmaps (value will be empty,
		// and we can't resolve them from here without additional permissions)
		if env.ValueFrom != nil {
			envMap[env.Name] = envEntry{Source: describeValueSource(env.ValueFrom)}
			continue
		}
		envMap[env.Name] = envEntry{Value: env.Value}
	}

	// Handle EnvFrom sources (ConfigMaps and Secrets mounted as env bundles)
	for _, envFrom := range container.EnvFrom {
		if envFrom.ConfigMapRef != nil {
			envMap[fmt.Sprintf("# [envFrom] configmap:%s", envFrom.ConfigMapRef.Name)] = envEntry{}
		} else if envFrom.SecretRef != nil {
			envMap[fmt.Sprintf("# [envFrom] secret:%s", envFrom.SecretRef.Name)] = envEntry{}
		}
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(envMap))
	for k := range envMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Write .env content
	var sb strings.Builder
	sb.WriteString("# Generated by 'diverge dev' — env vars from baseline pod\n")
	fmt.Fprintf(&sb, "# Source: %s/%s (container: %s)\n", pod.Namespace, pod.Name, container.Name)
	sb.WriteString("# Re-run 'diverge dev' to refresh.\n\n")

	written := 0
	for _, k := range keys {
		entry := envMap[k]
		if strings.HasPrefix(k, "# [envFrom]") {
			fmt.Fprintf(&sb, "%s\n", k)
		} else if entry.Source != "" {
			fmt.Fprintf(&sb, "# %s=# sourced from %s\n", k, entry.Source)
		} else {
			if strings.Contains(entry.Value, "\n") {
				fmt.Fprintf(&sb, "%s=%q\n", k, entry.Value)
			} else {
				fmt.Fprintf(&sb, "%s=%s\n", k, entry.Value)
			}
			written++
		}
	}

	if _, err := io.WriteString(out, sb.String()); err != nil {
		return 0, fmt.Errorf("failed to write env vars: %w", err)
	}

	return written, nil
}

// describeValueSource returns a human-readable description of where an env var
// value is sourced from (Secret, ConfigMap, etc).
func describeValueSource(vs *corev1.EnvVarSource) string {
	if vs.SecretKeyRef != nil {
		return fmt.Sprintf("secret:%s/%s", vs.SecretKeyRef.Name, vs.SecretKeyRef.Key)
	}
	if vs.ConfigMapKeyRef != nil {
		return fmt.Sprintf("configmap:%s/%s", vs.ConfigMapKeyRef.Name, vs.ConfigMapKeyRef.Key)
	}
	if vs.FieldRef != nil {
		return fmt.Sprintf("fieldRef:%s", vs.FieldRef.FieldPath)
	}
	if vs.ResourceFieldRef != nil {
		return fmt.Sprintf("resourceFieldRef:%s", vs.ResourceFieldRef.Resource)
	}
	return "unknown"
}

func findBaselinePod(ctx context.Context, clientset kubernetes.Interface, namespace, serviceName string) (*corev1.Pod, error) {
	labelSelectors := []string{
		fmt.Sprintf("app=%s,diverge.io/role=baseline", serviceName),
		fmt.Sprintf("app=%s", serviceName),
		fmt.Sprintf("app.kubernetes.io/name=%s", serviceName),
	}

	var pod *corev1.Pod
	var lastErr error
	for _, sel := range labelSelectors {
		listCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
		pods, err := clientset.CoreV1().Pods(namespace).List(listCtx, metav1.ListOptions{
			LabelSelector: sel,
			FieldSelector: "status.phase=Running",
		})
		cancel()
		if err != nil {
			lastErr = err
			continue
		}
		for i := range pods.Items {
			if pods.Items[i].Status.Phase == corev1.PodRunning {
				if pod == nil || pods.Items[i].Name < pod.Name {
					pod = &pods.Items[i]
				}
			}
		}
		if pod != nil {
			break
		}
	}

	if pod == nil {
		if lastErr != nil {
			return nil, fmt.Errorf("for service %q in namespace %q: %w (last error: %v)", serviceName, namespace, ErrBaselinePodNotFound, lastErr)
		}
		return nil, fmt.Errorf("for service %q in namespace %q: %w", serviceName, namespace, ErrBaselinePodNotFound)
	}
	return pod, nil
}

// resolveBaselineEnv resolves environment variables from a pod, including Secrets and ConfigMaps.
func resolveBaselineEnv(ctx context.Context, clientset kubernetes.Interface, pod *corev1.Pod) (map[string]string, error) {
	if len(pod.Spec.Containers) == 0 {
		return nil, fmt.Errorf("pod %q has no containers", pod.Name)
	}

	container := pod.Spec.Containers[0]
	envMap := make(map[string]string)
	ns := pod.Namespace

	hasSecret := false
	for _, env := range container.Env {
		if env.ValueFrom != nil && env.ValueFrom.SecretKeyRef != nil {
			hasSecret = true
			break
		}
	}
	if !hasSecret {
		for _, envFrom := range container.EnvFrom {
			if envFrom.SecretRef != nil {
				hasSecret = true
				break
			}
		}
	}

	if hasSecret && !strings.Contains(ns, "preview") {
		slog.Warn("resolving secrets from non-preview namespace", "namespace", ns)
	}

	isSecretVolume := func(v corev1.Volume) bool {
		return v.Secret != nil || v.Projected != nil
	}
	for _, vol := range pod.Spec.Volumes {
		if isSecretVolume(vol) {
			slog.Warn("Volume-mounted secret detected. Diverge does not currently sync volume mounts for local development.", "volume", vol.Name)
		}
	}

	getSecret := func(name string) (*corev1.Secret, error) {
		secret, err := clientset.CoreV1().Secrets(ns).Get(ctx, name, metav1.GetOptions{})
		if err != nil {
			return nil, fmt.Errorf("failed to get secret %q in namespace %q: %w", name, ns, err)
		}
		return secret, nil
	}

	getConfigMap := func(name string) (*corev1.ConfigMap, error) {
		cm, err := clientset.CoreV1().ConfigMaps(ns).Get(ctx, name, metav1.GetOptions{})
		if err != nil {
			return nil, fmt.Errorf("failed to get configmap %q in namespace %q: %w", name, ns, err)
		}
		return cm, nil
	}

	for _, env := range container.Env {
		if isKubeInjected(env.Name) {
			continue
		}

		if env.ValueFrom != nil {
			if env.ValueFrom.SecretKeyRef != nil {
				secret, err := getSecret(env.ValueFrom.SecretKeyRef.Name)
				if err != nil {
					return nil, err // Fail fast
				}
				if val, ok := secret.Data[env.ValueFrom.SecretKeyRef.Key]; ok {
					envMap[env.Name] = string(val)
				}
			} else if env.ValueFrom.ConfigMapKeyRef != nil {
				cm, err := getConfigMap(env.ValueFrom.ConfigMapKeyRef.Name)
				if err != nil {
					return nil, err
				}
				if val, ok := cm.Data[env.ValueFrom.ConfigMapKeyRef.Key]; ok {
					envMap[env.Name] = string(val)
				}
			}
		} else {
			envMap[env.Name] = env.Value
		}
	}

	for _, envFrom := range container.EnvFrom {
		if envFrom.SecretRef != nil {
			secret, err := getSecret(envFrom.SecretRef.Name)
			if err != nil {
				return nil, err // Fail fast
			}
			for k, v := range secret.Data {
				key := envFrom.Prefix + k
				if isKubeInjected(key) {
					continue
				}
				envMap[key] = string(v)
			}
		} else if envFrom.ConfigMapRef != nil {
			cm, err := getConfigMap(envFrom.ConfigMapRef.Name)
			if err != nil {
				return nil, err
			}
			for k, v := range cm.Data {
				key := envFrom.Prefix + k
				if isKubeInjected(key) {
					continue
				}
				envMap[key] = string(v)
			}
		}
	}

	return envMap, nil
}
