package cli

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func TestIsKubeInjected(t *testing.T) {
	tests := []struct {
		name     string
		envName  string
		injected bool
	}{
		{"kubernetes service host", "KUBERNETES_SERVICE_HOST", true},
		{"kubernetes service port", "KUBERNETES_SERVICE_PORT", true},
		{"kubernetes port", "KUBERNETES_PORT", true},
		{"service host pattern", "PAYMENTS_API_SERVICE_HOST", true},
		{"service port pattern", "PAYMENTS_API_SERVICE_PORT", true},
		{"port pattern", "PAYMENTS_API_PORT_8080_TCP", true},
		{"home", "HOME", true},
		{"hostname", "HOSTNAME", true},
		{"path", "PATH", true},
		{"app env", "DATABASE_URL", false},
		{"app env", "APP_VERSION", false},
		{"app env", "ACCOUNTS_API_URL", false},
		{"app env", "REDIS_URL", false},
		{"app env with port word", "SERVER_PORT", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isKubeInjected(tt.envName)
			assert.Equal(t, tt.injected, got, "isKubeInjected(%q)", tt.envName)
		})
	}
}

func TestSyncBaselineEnv(t *testing.T) {
	ctx := context.Background()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "payments-api-abc123",
			Namespace: "demo-bank",
			Labels: map[string]string{
				"app":             "payments-api",
				"diverge.io/role": "baseline",
			},
		},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{
				{
					Name:  "payments-api",
					Image: "payments-api:latest",
					Env: []corev1.EnvVar{
						{Name: "DATABASE_URL", Value: "postgres://localhost:5432/mydb"},
						{Name: "APP_VERSION", Value: "v1.2.3"},
						{Name: "ACCOUNTS_API_URL", Value: "http://accounts-api:8080"},
						{Name: "KUBERNETES_SERVICE_HOST", Value: "10.0.0.1"},
						{Name: "KUBERNETES_SERVICE_PORT", Value: "443"},
						{Name: "PAYMENTS_API_SERVICE_HOST", Value: "10.0.0.5"},
						{Name: "HOME", Value: "/root"},
						{Name: "PATH", Value: "/usr/local/bin:/usr/bin"},
						{
							Name: "SECRET_VAR",
							ValueFrom: &corev1.EnvVarSource{
								SecretKeyRef: &corev1.SecretKeySelector{
									LocalObjectReference: corev1.LocalObjectReference{Name: "my-secret"},
									Key:                  "api-key",
								},
							},
						},
					},
				},
			},
		},
	}

	clientset := fake.NewSimpleClientset(pod)

	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, ".env.diverge")

	synced, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "demo-bank",
		ServiceName: "payments-api",
		OutputPath:  outPath,
	})
	require.NoError(t, err)
	assert.Equal(t, 3, synced, "should sync 3 app env vars (DATABASE_URL, APP_VERSION, ACCOUNTS_API_URL)")

	content, err := os.ReadFile(outPath)
	require.NoError(t, err)
	contentStr := string(content)

	// Should contain app env vars
	assert.Contains(t, contentStr, "DATABASE_URL=postgres://localhost:5432/mydb")
	assert.Contains(t, contentStr, "APP_VERSION=v1.2.3")
	assert.Contains(t, contentStr, "ACCOUNTS_API_URL=http://accounts-api:8080")

	// Should NOT contain K8s-injected vars
	assert.NotContains(t, contentStr, "KUBERNETES_SERVICE_HOST")
	assert.NotContains(t, contentStr, "PAYMENTS_API_SERVICE_HOST")
	assert.NotContains(t, contentStr, "\nHOME=")
	assert.NotContains(t, contentStr, "\nPATH=")

	// Should have commented-out secret reference
	assert.Contains(t, contentStr, "# SECRET_VAR=# sourced from secret:my-secret/api-key")

	// Should have header comment
	assert.Contains(t, contentStr, "Generated by 'diverge dev'")

	// File should be 0600
	info, err := os.Stat(outPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0600), info.Mode().Perm(), "file should be owner-only readable")
}

func TestSyncBaselineEnv_NoPod(t *testing.T) {
	ctx := context.Background()
	clientset := fake.NewSimpleClientset() // empty cluster

	tmpDir := t.TempDir()

	_, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "demo-bank",
		ServiceName: "nonexistent-service",
		OutputPath:  filepath.Join(tmpDir, ".env.diverge"),
	})
	require.Error(t, err)
	require.ErrorIs(t, err, ErrBaselinePodNotFound)
}

func TestSyncBaselineEnv_InvalidServiceName(t *testing.T) {
	ctx := context.Background()
	clientset := fake.NewSimpleClientset()
	tmpDir := t.TempDir()

	tests := []struct {
		name        string
		serviceName string
	}{
		{"empty", ""},
		{"too long", strings.Repeat("a", 64)},
		{"starts with dash", "-payments"},
		{"contains spaces", "my service"},
		{"uppercase not valid label", "My.Service/Name"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
				Namespace:   "default",
				ServiceName: tt.serviceName,
				OutputPath:  filepath.Join(tmpDir, ".env.diverge"),
			})
			require.Error(t, err)
			require.ErrorIs(t, err, ErrInvalidServiceName)
		})
	}
}

func TestSyncBaselineEnv_FallbackLabelSelector(t *testing.T) {
	ctx := context.Background()

	// Pod without diverge.io/role label — should still be found via "app=svc" selector
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "gateway-xyz",
			Namespace: "default",
			Labels: map[string]string{
				"app": "gateway",
			},
		},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{
				{
					Name:  "gateway",
					Image: "gateway:latest",
					Env: []corev1.EnvVar{
						{Name: "UPSTREAM_URL", Value: "http://backend:8080"},
					},
				},
			},
		},
	}

	clientset := fake.NewSimpleClientset(pod)
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, ".env.diverge")

	synced, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "default",
		ServiceName: "gateway",
		OutputPath:  outPath,
	})
	require.NoError(t, err)
	assert.Equal(t, 1, synced)

	content, err := os.ReadFile(outPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "UPSTREAM_URL=http://backend:8080")
}

func TestSyncBaselineEnv_ConfigMapRef(t *testing.T) {
	ctx := context.Background()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "svc-abc",
			Namespace: "default",
			Labels:    map[string]string{"app": "svc"},
		},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{
				{
					Name:  "svc",
					Image: "svc:latest",
					Env: []corev1.EnvVar{
						{
							Name: "CONFIG_VALUE",
							ValueFrom: &corev1.EnvVarSource{
								ConfigMapKeyRef: &corev1.ConfigMapKeySelector{
									LocalObjectReference: corev1.LocalObjectReference{Name: "app-config"},
									Key:                  "setting",
								},
							},
						},
					},
				},
			},
		},
	}

	clientset := fake.NewSimpleClientset(pod)
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, ".env.diverge")

	synced, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "default",
		ServiceName: "svc",
		OutputPath:  outPath,
	})
	require.NoError(t, err)
	assert.Equal(t, 0, synced, "secret/configmap refs are commented out, not counted")

	content, err := os.ReadFile(outPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "# CONFIG_VALUE=# sourced from configmap:app-config/setting")
}

func TestSyncBaselineEnv_EnvFrom(t *testing.T) {
	ctx := context.Background()

	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "svc-envfrom",
			Namespace: "default",
			Labels:    map[string]string{"app": "svc-envfrom"},
		},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{
				{
					Name:  "svc",
					Image: "svc:latest",
					EnvFrom: []corev1.EnvFromSource{
						{
							ConfigMapRef: &corev1.ConfigMapEnvSource{
								LocalObjectReference: corev1.LocalObjectReference{Name: "app-settings"},
							},
						},
						{
							SecretRef: &corev1.SecretEnvSource{
								LocalObjectReference: corev1.LocalObjectReference{Name: "db-creds"},
							},
						},
					},
				},
			},
		},
	}

	clientset := fake.NewSimpleClientset(pod)
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, ".env.diverge")

	synced, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "default",
		ServiceName: "svc-envfrom",
		OutputPath:  outPath,
	})
	require.NoError(t, err)
	assert.Equal(t, 0, synced, "envFrom annotations are not counted as synced vars")

	content, err := os.ReadFile(outPath)
	require.NoError(t, err)
	contentStr := string(content)

	// Should have envFrom annotations
	assert.Contains(t, contentStr, "# [envFrom] configmap:app-settings")
	assert.Contains(t, contentStr, "# [envFrom] secret:db-creds")
	// File should still be written (not skipped)
	assert.Contains(t, contentStr, "Generated by 'diverge dev'")
}

func TestSyncBaselineEnv_StaleFileTruncated(t *testing.T) {
	ctx := context.Background()

	// Pod with no env vars at all
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "empty-svc-abc",
			Namespace: "default",
			Labels:    map[string]string{"app": "empty-svc"},
		},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{
				{
					Name:  "svc",
					Image: "svc:latest",
					// No Env or EnvFrom
				},
			},
		},
	}

	clientset := fake.NewSimpleClientset(pod)
	tmpDir := t.TempDir()
	outPath := filepath.Join(tmpDir, ".env.diverge")

	// Write stale content first
	require.NoError(t, os.WriteFile(outPath, []byte("STALE_VAR=old_value\n"), 0600))

	synced, err := syncBaselineEnv(ctx, clientset, syncEnvOptions{
		Namespace:   "default",
		ServiceName: "empty-svc",
		OutputPath:  outPath,
	})
	require.NoError(t, err)
	assert.Equal(t, 0, synced)

	// Stale content should be replaced with header-only file
	content, err := os.ReadFile(outPath)
	require.NoError(t, err)
	contentStr := string(content)
	assert.NotContains(t, contentStr, "STALE_VAR")
	assert.Contains(t, contentStr, "Generated by 'diverge dev'")
}

func TestDescribeValueSource(t *testing.T) {
	tests := []struct {
		name     string
		source   *corev1.EnvVarSource
		contains string
	}{
		{
			"secret",
			&corev1.EnvVarSource{SecretKeyRef: &corev1.SecretKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "db-creds"},
				Key:                  "password",
			}},
			"secret:db-creds/password",
		},
		{
			"configmap",
			&corev1.EnvVarSource{ConfigMapKeyRef: &corev1.ConfigMapKeySelector{
				LocalObjectReference: corev1.LocalObjectReference{Name: "settings"},
				Key:                  "log-level",
			}},
			"configmap:settings/log-level",
		},
		{
			"fieldRef",
			&corev1.EnvVarSource{FieldRef: &corev1.ObjectFieldSelector{FieldPath: "metadata.name"}},
			"fieldRef:metadata.name",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := describeValueSource(tt.source)
			assert.True(t, strings.Contains(result, tt.contains), "describeValueSource: got %q, want contains %q", result, tt.contains)
		})
	}
}
