{{- if .Values.activatorProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diverge.fullname" . }}-activator-proxy
  labels:
    {{- include "diverge.labels" . | nindent 4 }}
    app.kubernetes.io/component: activator-proxy
{{- end }}
