apiVersion: v1
kind: Service
metadata:
  name: {{ include "diverge.fullname" . }}-webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.port }}
  selector:
    control-plane: controller-manager
