{{- if .Values.server.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diverge.fullname" . }}-server
  labels:
    {{- include "diverge.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
{{- end }}
